// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__parse_lazy = 9264
    _entry__load_lazy = 224
)

const (
    _stack__parse_lazy = 544
    _stack__load_lazy = 272
)

const (
    _size__parse_lazy = 11828
    _size__load_lazy = 7596
)

var (
    _pcsp__parse_lazy = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {11634, 272},
        {11635, 264},
        {11637, 256},
        {11639, 248},
        {11641, 240},
        {11643, 232},
        {11647, 224},
        {11828, 272},
    }
    _pcsp__load_lazy = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {7581, 272},
        {7582, 264},
        {7584, 256},
        {7586, 248},
        {7588, 240},
        {7590, 232},
        {7596, 224},
    }
)

var _cfunc_parse_lazy = []loader.CFunc{
    {"_parse_lazy_entry", 0,  _entry__parse_lazy, 0, nil},
    {"_parse_lazy", _entry__parse_lazy, _size__parse_lazy, _stack__parse_lazy, _pcsp__parse_lazy},
}
var _cfunc_load_lazy = []loader.CFunc{
    {"_load_lazy_entry", 0,  _entry__load_lazy, 0, nil},
    {"_load_lazy", _entry__load_lazy, _size__load_lazy, _stack__load_lazy, _pcsp__load_lazy},
}
