// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package avx2

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__parse_lazy = 10144
    _entry__load_lazy = 624
)

const (
    _stack__parse_lazy = 480
    _stack__load_lazy = 240
)

const (
    _size__parse_lazy = 11792
    _size__load_lazy = 7848
)

var (
    _pcsp__parse_lazy = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {11508, 240},
        {11509, 232},
        {11511, 224},
        {11513, 216},
        {11515, 208},
        {11517, 200},
        {11521, 192},
        {11792, 240},
    }
    _pcsp__load_lazy = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {7511, 240},
        {7512, 232},
        {7514, 224},
        {7516, 216},
        {7518, 208},
        {7520, 200},
        {7524, 192},
        {7848, 240},
    }
)

var _cfunc_parse_lazy = []loader.CFunc{
    {"_parse_lazy_entry", 0,  _entry__parse_lazy, 0, nil},
    {"_parse_lazy", _entry__parse_lazy, _size__parse_lazy, _stack__parse_lazy, _pcsp__parse_lazy},
}
var _cfunc_load_lazy = []loader.CFunc{
    {"_load_lazy_entry", 0,  _entry__load_lazy, 0, nil},
    {"_load_lazy", _entry__load_lazy, _size__load_lazy, _stack__load_lazy, _pcsp__load_lazy},
}
