// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package neon

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__f32toa = 106472
    _entry__f64toa = 96
    _entry__fsm_exec = 36688
    _entry__get_by_path = 89008
    _entry__html_escape = 11456
    _entry__i64toa = 4128
    _entry__lspace = 16
    _entry__quote = 8208
    _entry__skip_array = 49792
    _entry__skip_number = 68560
    _entry__skip_object = 59184
    _entry__skip_one = 69648
    _entry__skip_one_fast = 85456
    _entry__u64toa = 6816
    _entry__unquote = 9664
    _entry__validate_one = 79040
    _entry__validate_utf8 = 105304
    _entry__validate_utf8_fast = 105960
    _entry__value = 17424
    _entry__vnumber = 29720
    _entry__vsigned = 35960
    _entry__vstring = 27712
    _entry__vunsigned = 36328
)

const (
    _stack__f32toa = 0
    _stack__f64toa = 16
    _stack__fsm_exec = 112
    _stack__get_by_path = 192
    _stack__html_escape = 16
    _stack__i64toa = 0
    _stack__lspace = 0
    _stack__quote = 0
    _stack__skip_array = 112
    _stack__skip_number = 32
    _stack__skip_object = 112
    _stack__skip_one = 112
    _stack__skip_one_fast = 128
    _stack__u64toa = 0
    _stack__unquote = 96
    _stack__validate_one = 112
    _stack__validate_utf8 = 32
    _stack__validate_utf8_fast = 16
    _stack__value = 64
    _stack__vnumber = 80
    _stack__vsigned = 0
    _stack__vstring = 16
    _stack__vunsigned = 0
)

const (
    _size__f32toa = 2744
    _size__f64toa = 3976
    _size__fsm_exec = 8280
    _size__get_by_path = 15484
    _size__html_escape = 1072
    _size__i64toa = 2632
    _size__lspace = 80
    _size__quote = 1424
    _size__skip_array = 8524
    _size__skip_number = 1008
    _size__skip_object = 8524
    _size__skip_one = 8524
    _size__skip_one_fast = 592
    _size__u64toa = 1360
    _size__unquote = 1760
    _size__validate_one = 5472
    _size__validate_utf8 = 656
    _size__validate_utf8_fast = 512
    _size__value = 9340
    _size__vnumber = 6240
    _size__vsigned = 368
    _size__vstring = 2008
    _size__vunsigned = 328
)

var (
    _pcsp__f32toa = [][2]uint32{
        {2744, 0},
    }
    _pcsp__f64toa = [][2]uint32{
        {532, 16},
        {536, 0},
        {1848, 16},
        {1852, 0},
        {2288, 16},
        {2292, 0},
        {2368, 16},
        {2372, 0},
        {2392, 16},
        {2396, 0},
        {3192, 16},
        {3196, 0},
        {3756, 16},
        {3760, 0},
        {3776, 16},
        {3780, 0},
        {3864, 16},
        {3868, 0},
        {3976, 16},
    }
    _pcsp__fsm_exec = [][2]uint32{
        {8220, 112},
        {8224, 0},
        {8276, 112},
    }
    _pcsp__get_by_path = [][2]uint32{
        {14992, 192},
        {14996, 0},
        {15484, 192},
    }
    _pcsp__html_escape = [][2]uint32{
        {1008, 16},
        {1012, 0},
        {1040, 16},
        {1044, 0},
        {1064, 16},
        {1072, 0},
    }
    _pcsp__i64toa = [][2]uint32{
        {2628, 0},
    }
    _pcsp__lspace = [][2]uint32{
        {80, 0},
    }
    _pcsp__quote = [][2]uint32{
        {1424, 0},
    }
    _pcsp__skip_array = [][2]uint32{
        {8464, 112},
        {8468, 0},
        {8520, 112},
    }
    _pcsp__skip_number = [][2]uint32{
        {112, 32},
        {116, 0},
        {800, 32},
        {804, 0},
        {868, 32},
        {872, 0},
        {980, 32},
        {984, 0},
        {1004, 32},
    }
    _pcsp__skip_object = [][2]uint32{
        {8464, 112},
        {8468, 0},
        {8520, 112},
    }
    _pcsp__skip_one = [][2]uint32{
        {8464, 112},
        {8468, 0},
        {8520, 112},
    }
    _pcsp__skip_one_fast = [][2]uint32{
        {552, 128},
        {556, 0},
        {588, 128},
    }
    _pcsp__u64toa = [][2]uint32{
        {1352, 0},
    }
    _pcsp__unquote = [][2]uint32{
        {1128, 96},
        {1132, 0},
        {1752, 96},
    }
    _pcsp__validate_one = [][2]uint32{
        {5408, 112},
        {5412, 0},
        {5468, 112},
    }
    _pcsp__validate_utf8 = [][2]uint32{
        {608, 32},
        {612, 0},
        {628, 32},
        {632, 0},
        {648, 32},
        {656, 0},
    }
    _pcsp__validate_utf8_fast = [][2]uint32{
        {488, 16},
        {492, 0},
        {504, 16},
        {512, 0},
    }
    _pcsp__value = [][2]uint32{
        {308, 64},
        {312, 0},
        {1488, 64},
        {1492, 0},
        {3272, 64},
        {3276, 0},
        {3360, 64},
        {3364, 0},
        {3392, 64},
        {3396, 0},
        {3924, 64},
        {3928, 0},
        {4244, 64},
        {4248, 0},
        {5408, 64},
        {5412, 0},
        {9336, 64},
    }
    _pcsp__vnumber = [][2]uint32{
        {396, 80},
        {400, 0},
        {776, 80},
        {780, 0},
        {2348, 80},
        {2352, 0},
        {6240, 80},
    }
    _pcsp__vsigned = [][2]uint32{
        {368, 0},
    }
    _pcsp__vstring = [][2]uint32{
        {948, 16},
        {952, 0},
        {1880, 16},
        {1884, 0},
        {1904, 16},
        {1908, 0},
        {2000, 16},
        {2008, 0},
    }
    _pcsp__vunsigned = [][2]uint32{
        {328, 0},
    }
)

var Funcs = []loader.CFunc{
    {"__native_entry__", 0, 64, 0, nil},
    {"_f32toa", _entry__f32toa, _size__f32toa, _stack__f32toa, _pcsp__f32toa},
    {"_f64toa", _entry__f64toa, _size__f64toa, _stack__f64toa, _pcsp__f64toa},
    {"_fsm_exec", _entry__fsm_exec, _size__fsm_exec, _stack__fsm_exec, _pcsp__fsm_exec},
    {"_get_by_path", _entry__get_by_path, _size__get_by_path, _stack__get_by_path, _pcsp__get_by_path},
    {"_html_escape", _entry__html_escape, _size__html_escape, _stack__html_escape, _pcsp__html_escape},
    {"_i64toa", _entry__i64toa, _size__i64toa, _stack__i64toa, _pcsp__i64toa},
    {"_lspace", _entry__lspace, _size__lspace, _stack__lspace, _pcsp__lspace},
    {"_quote", _entry__quote, _size__quote, _stack__quote, _pcsp__quote},
    {"_skip_array", _entry__skip_array, _size__skip_array, _stack__skip_array, _pcsp__skip_array},
    {"_skip_number", _entry__skip_number, _size__skip_number, _stack__skip_number, _pcsp__skip_number},
    {"_skip_object", _entry__skip_object, _size__skip_object, _stack__skip_object, _pcsp__skip_object},
    {"_skip_one", _entry__skip_one, _size__skip_one, _stack__skip_one, _pcsp__skip_one},
    {"_skip_one_fast", _entry__skip_one_fast, _size__skip_one_fast, _stack__skip_one_fast, _pcsp__skip_one_fast},
    {"_u64toa", _entry__u64toa, _size__u64toa, _stack__u64toa, _pcsp__u64toa},
    {"_unquote", _entry__unquote, _size__unquote, _stack__unquote, _pcsp__unquote},
    {"_validate_one", _entry__validate_one, _size__validate_one, _stack__validate_one, _pcsp__validate_one},
    {"_validate_utf8", _entry__validate_utf8, _size__validate_utf8, _stack__validate_utf8, _pcsp__validate_utf8},
    {"_validate_utf8_fast", _entry__validate_utf8_fast, _size__validate_utf8_fast, _stack__validate_utf8_fast, _pcsp__validate_utf8_fast},
    {"_value", _entry__value, _size__value, _stack__value, _pcsp__value},
    {"_vnumber", _entry__vnumber, _size__vnumber, _stack__vnumber, _pcsp__vnumber},
    {"_vsigned", _entry__vsigned, _size__vsigned, _stack__vsigned, _pcsp__vsigned},
    {"_vstring", _entry__vstring, _size__vstring, _stack__vstring, _pcsp__vstring},
    {"_vunsigned", _entry__vunsigned, _size__vunsigned, _stack__vunsigned, _pcsp__vunsigned},
}
